#!/usr/bin/env bash
# Build Path: /app/.heroku/python/

OUT_PREFIX=$1

echo "Building SQLite..."


SOURCE_TARBALL='http://ftp.osuosl.org/pub/blfs/conglomeration/sqlite/sqlite-autoconf-3080600.tar.gz'

curl $SOURCE_TARBALL | tar xz
# jx
mv sqlite-autoconf-3080600 sqlite

cd sqlite
export CFLAGS='-DSQLITE_ENABLE_COLUMN_METADATA'
./configure --prefix=$OUT_PREFIX
make
make install

# Cleanup
cd ..
rm -fr sqlite
